---
title: "HW5"
author: "Sarahy Martinez"
date: "2024-11-05"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
library(stringr)
library(tibble)

```


## Problem 1 

```{r}

same_birthday = function(n) { 
  birthday = sample(1:365, n, replace = TRUE)
  return(length(birthday) != length(unique(birthday))) 
  }

n = 30 
results = same_birthday(n) 

# False -> all birthdays are unique , TRUE -> there are duplicate birthdays 

```

```{r}

simulate_probabilities = function(group_size, num_simulations) {
  results = map(1:num_simulations, ~same_birthday(group_size))
  mean(unlist(results)) }

group_sizes = 2:50 
probabilities = map_dbl(group_sizes, ~simulate_probabilities(.x, 10000))


results_table = tibble(
  group_size = group_sizes, probability = probabilities)

```

```{r}

ggplot( results_table, aes( x = group_size, y = probability)) + geom_line() + geom_point()+
  labs (
    title = "Group Size vs Probaility of Same Birthday ",
    x = "Group Size",
    y = "Probability"
  )

```


## Problem 2

```{r}

sim_power= function(mu, n = 30, sigma = 5, datasets = 5000, alpha = 0.05) {
  results = replicate(datasets, {
    x = rnorm(n, mean = mu, sd = sigma)
    test = t.test(x, mu = 0)
    broom::tidy(test)
  }, simplify = FALSE)
  
  results_df = bind_rows(results)
  
  power = mean(results_df$p.value < alpha)
  
  return(list(mu_hat = mean(results_df$estimate), power = power))
}


mu_values =0:6

results = vector("list", length(mu_values))

for( i in 1:length(mu_values)){
  mu = mu_values[i]
  results[[i]] = sim_power(mu)

}


results_df =
  bind_rows(results) %>% 
  mutate(mu = mu_values)
  

```


```{r}

ggplot( results_df, aes( x = mu, y = power)) + geom_line() + geom_point()+
  labs (
    title = " Proportion of Times Null Was Rejected vs Mu",
    x = "True Value of Mu",
    y = "Power"
  )




```
Based  on the graph we can see that as effect size increases so does power. There is a positive association until we reach mu=5 and mu =6 where power starts to plateau and even out. 




























